name: py

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: install
        run: |
          pip3 install --upgrade pip
          make install

      - name: pytest
        run: |
          make pytest
